version: '3.8'
services:
  app:
    build: .
    ports:
      - "80:80"
    restart: always
    environment:
      VITE_NODE_ENV: production
    command: serve -s dist --listen 80
    volumes:
      - /app/node_modules
