version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist:/usr/share/nginx/html:ro
    depends_on:
      - frontend
    networks:
      - public_network
      - host_network  # Nova rede para acesso ao host

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react_app
    restart: always
    environment:
      - VITE_NODE_ENV=production
      - VITE_API_URL=http://10.0.2.100:8080/api/v1/
    networks:
      - public_network
    volumes:
      - ./dist:/app/dist:ro

networks:
  public_network:
    driver: bridge
  host_network:
    driver: host  # Permite acesso à rede do host