version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist:/usr/share/nginx/html:ro
    networks:
      - public_network
      - host_network  # Rede para acessar a API privada

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react_app
    restart: always
    environment:
      - VITE_NODE_ENV=production
      - VITE_API_URL=/api/v1/
      - VITE_API_URL_WS=/ws-notifications
    networks:
      - public_network  # Só precisa da rede pública

networks:
  public_network:
    driver: bridge
  host_network:
    driver: bridge
    # Configuração adicional se a API estiver em outra rede Docker:
    # external: true
    # name: rede-da-api