version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./certbot-www:/var/www/certbot
    networks:
      - public_network
      - host_network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./certbot-www:/var/www/certbot
    entrypoint: >
      sh -c "certbot certonly --webroot --webroot-path=/var/www/certbot
      --email jonatha.carvalho0503@gmail.com --agree-tos --no-eff-email
      -d orderhub.zapto.org"

  frontend:
    image: jonathancarvalho039/front-end-app
    container_name: react_app
    restart: always
    networks:
      - public_network

volumes:
  certbot-etc:
  certbot-var:

networks:
  public_network:
    driver: bridge
  host_network:
    driver: bridge
