version: '3.8'
services:
  app:
    build: .
    ports:
      - "5173:5173"
    restart: always
    environment:
      NODE_ENV: production
    command: serve -s dist --listen 5173
    volumes:
      - .:/app
      - /app/node_modules
