version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist:/usr/share/nginx/html:ro
      - /opt/ssl_certbot/www:/var/www/certbot  # Remova :ro para permitir escrita
      - /opt/ssl_certbot/conf:/etc/letsencrypt:ro
      - /etc/nginx/dhparam.pem:/etc/nginx/dhparam.pem:ro
    networks:
      - public_network
      - host_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/.well-known/acme-challenge/test"]
      interval: 30s
      timeout: 5s
      retries: 3

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /opt/ssl_certbot/www:/var/www/certbot
      - /opt/ssl_certbot/conf:/etc/letsencrypt
    command: >
      sh -c 'while ! curl -s http://nginx/.well-known/acme-challenge/test >/dev/null; do
        echo "Waiting for nginx...";
        sleep 5;
      done;
      certbot certonly --webroot -w /var/www/certbot
      --keep-until-expiring --agree-tos --no-eff-email
      --email jonatha.carvalho0503@gmail.com
      -d orderhub.zapto.org;
      echo "Certificate obtained!"'
    depends_on:
      nginx:
        condition: service_healthy
    networks:
      - public_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react_app
    restart: always
    environment:
      - VITE_NODE_ENV=production
      - VITE_API_URL=/api/v1/
      - VITE_API_URL_WS=/ws-notifications
    networks:
      - public_network

networks:
  public_network:
    driver: bridge
  host_network:
    driver: bridge