name: CI

on:
  workflow_run:
    workflows: ["Build and Deploy Docker Image"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        run: |
          sudo docker-compose down
          sudo docker pull jonathancarvalho039/front-end-app:latest
          sudo docker-compose up -d
