name: Deploy to Production

on:
  workflow_run:
    workflows: ["Build and Deploy Docker Image"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Pull and Restart Container
        run: |
          echo "Pulling new image..."
          sudo docker pull jonathancarvalho039/front-end-app:latest

          echo "Stopping existing containers..."
          sudo docker-compose down

          echo "Starting updated containers..."
          sudo docker-compose up -d
