name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # Instalar dependências
      - name: Install Node.js dependencies
        run: |
          npm install

      # Build da aplicação Vite
      - name: Build Vite React App
        run: |
          npm run build

      # Login no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build da imagem usando docker-compose
      - name: Build Docker Image
        run: |
          docker-compose build

      # Tag da imagem
      - name: Tag Docker Image
        run: |
          docker tag front-end-app jonathancarvalho039/front-end-app:latest

      # Push para o Docker Hub
      - name: Push Docker Image
        run: |
          docker push jonathancarvalho039/front-end-app:latest
